Kunstmaan\NodeBundle\Entity\NodeTranslation:
  exclusion_policy: ALL

  properties:
    lang:
      expose: true
      groups: [edit, create]
    online:
      expose: true
      groups: [edit, create]
    title:
      expose: true
      groups: [edit, create]
    weight:
      expose: true
      groups: [edit, create]
    created:
      expose: true
    updated:
      expose: true
    url:
      expose: true
    slug:
      expose: true

  relations:
    -
      rel: self
      href: expr('/api/nodes/' ~ object.getNode().getId() ~ '/translations')